'use client';

import { useCallback, useEffect, useState } from 'react';
import { Copy, KeyRound, ShieldCheck, Trash2, Webhook } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuthFetch } from '@/components/AuthProvider';
import type { PassportDeveloperScope, PassportDeveloperToken } from '@/lib/passport-connections-types';

const SCOPE_OPTIONS: Array<{ key: PassportDeveloperScope; label: string }> = [
  { key: 'passport.summary:read', label: 'Identity and summary' }, { key: 'passport.games:read', label: 'Visible game library facts' }, { key: 'passport.competition:read', label: 'Competitive summary' }, { key: 'passport.events:read', label: 'Event history' }, { key: 'passport.achievements:read', label: 'Achievement cabinet' }, { key: 'webhooks:manage', label: 'Manage webhooks' },
];
type Subscription = { id: string; endpoint_url: string; event_types: string[]; status: string; failure_count: number; last_success_at: string | null };
type Rollout = { enabled: boolean; reason: string | null };
export function PassportDeveloperConsole() {
  const authFetch = useAuthFetch(); const [tokens, setTokens] = useState<PassportDeveloperToken[]>([]); const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [rollout, setRollout] = useState<Rollout | null>(null); const [label, setLabel] = useState('My Passport app'); const [scopes, setScopes] = useState<PassportDeveloperScope[]>(['passport.summary:read']); const [revealedToken, setRevealedToken] = useState(''); const [revealedSecret, setRevealedSecret] = useState(''); const [tokenId, setTokenId] = useState(''); const [endpoint, setEndpoint] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const [tokensResponse, hooksResponse] = await Promise.all([authFetch('/api/passport/developer-tokens'), authFetch('/api/passport/webhooks')]); const [tokensPayload, hooksPayload] = await Promise.all([tokensResponse.json(), hooksResponse.json()]); if (tokensResponse.ok) { setTokens(tokensPayload.tokens ?? []); setRollout(tokensPayload.rollout ?? null); } if (hooksResponse.ok) setSubscriptions(hooksPayload.subscriptions ?? []); }, [authFetch]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function createToken(event: React.FormEvent) { event.preventDefault(); setSaving(true); const response = await authFetch('/api/passport/developer-tokens', { method: 'POST', body: JSON.stringify({ label, scopes }) }); const payload = await response.json(); setSaving(false); if (!response.ok) return toast.error(payload.error ?? 'Could not create token'); setRevealedToken(payload.token); setTokenId(payload.record.id); toast.success('API token created. Copy it now.'); await load(); }
  async function revoke(id: string) { const response = await authFetch('/api/passport/developer-tokens', { method: 'DELETE', body: JSON.stringify({ id }) }); if (!response.ok) return toast.error('Could not revoke token'); toast.success('API token revoked'); await load(); }
  async function createWebhook(event: React.FormEvent) { event.preventDefault(); setSaving(true); const response = await authFetch('/api/passport/webhooks', { method: 'POST', body: JSON.stringify({ developer_token_id: tokenId, endpoint_url: endpoint, event_types: ['passport.updated', 'game.imported', 'achievement.issued', 'achievement.revoked', 'event.credential_issued', 'event.credential_revoked'] }) }); const payload = await response.json(); setSaving(false); if (!response.ok) return toast.error(payload.error ?? 'Could not create webhook'); setRevealedSecret(payload.secret); toast.success('Webhook registered. Copy its signing secret now.'); await load(); }
  async function copy(value: string) { await navigator.clipboard.writeText(value); toast.success('Copied'); }
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-7 sm:px-7"><header className="card p-6 sm:p-8"><p className="brand-kicker">Portable Gamer Passport</p><h1 className="mt-3 text-3xl font-black text-[var(--text-primary)]">Developer access you control</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]">Create narrowly scoped tokens for your own Passport. Raw tokens and webhook secrets appear once, are stored only as hashes or encrypted envelopes, and can be revoked without changing your Mechi login.</p></header>
    {rollout && !rollout.enabled ? <section className="rounded-3xl border border-amber-400/30 bg-amber-400/10 p-5"><p className="font-black text-amber-600">Developer access is in controlled rollout</p><p className="mt-2 text-sm text-[var(--text-secondary)]">{rollout.reason}. Existing credentials remain visible and revocable.</p></section> : null}
    {revealedToken ? <section className="rounded-3xl border border-amber-400/30 bg-amber-400/10 p-5"><p className="text-xs font-black uppercase tracking-wide text-amber-600">Copy this token now — it will not be shown again</p><div className="mt-3 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-xl bg-black/70 p-3 text-xs text-white">{revealedToken}</code><button aria-label="Copy API token" className="btn-outline" onClick={() => void copy(revealedToken)}><Copy size={16}/></button></div></section> : null}
    <section className="grid gap-6 lg:grid-cols-2"><form onSubmit={createToken} className="card p-6"><div className="flex items-center gap-2"><KeyRound className="text-[var(--brand-teal)]"/><h2 className="text-xl font-black text-[var(--text-primary)]">New API token</h2></div><label className="mt-5 block"><span className="label">Token label</span><input className="input-field mt-2" minLength={2} maxLength={60} value={label} onChange={(event) => setLabel(event.target.value)}/></label><fieldset className="mt-5"><legend className="label">Granted scopes</legend><div className="mt-3 space-y-2">{SCOPE_OPTIONS.map((scope) => <label key={scope.key} className="flex items-center gap-2 text-sm text-[var(--text-secondary)]"><input type="checkbox" checked={scopes.includes(scope.key)} onChange={(event) => setScopes((current) => event.target.checked ? [...current, scope.key] : current.filter((value) => value !== scope.key))}/><span><span className="font-bold text-[var(--text-primary)]">{scope.label}</span><span className="ml-2 text-xs text-[var(--text-soft)]">{scope.key}</span></span></label>)}</div></fieldset><button disabled={saving || !scopes.length || rollout?.enabled === false} className="btn-primary mt-5 inline-flex items-center gap-2"><KeyRound size={15}/>Create token</button></form>
      <section className="card p-6"><h2 className="text-xl font-black text-[var(--text-primary)]">Active and revoked tokens</h2><div className="mt-5 space-y-2">{tokens.map((token) => <div key={token.id} className="rounded-2xl border border-[var(--border)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-[var(--text-primary)]">{token.label}</p><p className="mt-1 font-mono text-xs text-[var(--text-soft)]">{token.token_prefix}••••••••</p></div>{!token.revoked_at ? <button aria-label={`Revoke ${token.label}`} onClick={() => void revoke(token.id)} className="text-rose-500"><Trash2 size={16}/></button> : <span className="text-xs font-bold text-[var(--text-soft)]">Revoked</span>}</div><p className="mt-3 text-xs leading-5 text-[var(--text-soft)]">{token.scopes.join(' · ')}</p></div>)}{!tokens.length ? <p className="text-sm text-[var(--text-soft)]">No API tokens yet.</p> : null}</div></section></section>
    <section className="card p-6"><div className="flex items-center gap-2"><Webhook className="text-[var(--brand-teal)]"/><h2 className="text-xl font-black text-[var(--text-primary)]">Webhook subscriptions</h2></div><p className="mt-2 text-sm text-[var(--text-secondary)]">Delivery is controlled by a separate operator kill switch. Endpoints must be public HTTPS and are pinned to a validated public address for each attempt.</p>{revealedSecret ? <div className="mt-4 rounded-2xl bg-amber-400/10 p-4"><p className="text-xs font-black text-amber-600">One-time signing secret</p><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-xl bg-black/70 p-3 text-xs text-white">{revealedSecret}</code><button aria-label="Copy webhook secret" onClick={() => void copy(revealedSecret)}><Copy size={16}/></button></div></div> : null}<form onSubmit={createWebhook} className="mt-5 grid gap-3 md:grid-cols-[.8fr_1.2fr_auto]"><select required className="input-field" value={tokenId} onChange={(event) => setTokenId(event.target.value)}><option value="">Token with webhooks:manage</option>{tokens.filter((token) => !token.revoked_at && token.scopes.includes('webhooks:manage')).map((token) => <option key={token.id} value={token.id}>{token.label}</option>)}</select><input required type="url" className="input-field" placeholder="https://example.com/webhooks/mechi" value={endpoint} onChange={(event) => setEndpoint(event.target.value)}/><button disabled={saving || rollout?.enabled === false} className="btn-outline">Register</button></form><div className="mt-5 grid gap-2 md:grid-cols-2">{subscriptions.map((subscription) => <div key={subscription.id} className="rounded-2xl border border-[var(--border)] p-4"><p className="truncate font-bold text-[var(--text-primary)]">{subscription.endpoint_url}</p><p className="mt-2 text-xs text-[var(--text-soft)]">{subscription.status} · {subscription.event_types.length} events · {subscription.failure_count} failures</p></div>)}</div><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-[var(--text-soft)]"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-[var(--brand-teal)]"/>The API returns only scopes listed on the token. A developer token never grants account changes, private credentials, contact details, payouts, or Mechi administration.</p></section>
    <section className="card p-6"><p className="brand-kicker">API contract</p><h2 className="mt-2 text-xl font-black text-[var(--text-primary)]">Read your authorized Passport</h2><pre className="mt-4 overflow-x-auto rounded-2xl bg-black/80 p-4 text-xs text-white"><code>{`curl https://mechi.club/api/v1/passport \\\n  -H "Authorization: Bearer mcp_your_token"`}</code></pre></section>
  </main>;
}
