export type CodmWeek1LeaderboardRow = {
  finalPoints: number;
  killPoints: number;
  kills: [number, number, number];
  placementPoints: [number, number, number];
  player: string;
  totalKills: number;
  totalPlacementPoints: number;
};

export const CODM_WEEK1_LEADERBOARD_ROWS: CodmWeek1LeaderboardRow[] = [
  {
    player: 'Σи | WhyNotक्र',
    kills: [5, 8, 6],
    placementPoints: [20, 20, 15],
    totalKills: 19,
    totalPlacementPoints: 55,
    killPoints: 57,
    finalPoints: 112,
  },
  {
    player: 'Λp · Ranxxsஜ',
    kills: [6, 2, 3],
    placementPoints: [10, 5, 10],
    totalKills: 11,
    totalPlacementPoints: 25,
    killPoints: 33,
    finalPoints: 58,
  },
  {
    player: 'Σи | HateΛp',
    kills: [1, 4, 5],
    placementPoints: [3, 3, 20],
    totalKills: 10,
    totalPlacementPoints: 26,
    killPoints: 30,
    finalPoints: 56,
  },
  {
    player: 'White',
    kills: [8, 0, 2],
    placementPoints: [3, 0, 3],
    totalKills: 10,
    totalPlacementPoints: 6,
    killPoints: 30,
    finalPoints: 36,
  },
  {
    player: 'Vibes 來',
    kills: [0, 7, 0],
    placementPoints: [0, 10, 3],
    totalKills: 7,
    totalPlacementPoints: 13,
    killPoints: 21,
    finalPoints: 34,
  },
  {
    player: '╳DS.BAKI',
    kills: [2, 1, 2],
    placementPoints: [5, 10, 3],
    totalKills: 5,
    totalPlacementPoints: 18,
    killPoints: 15,
    finalPoints: 33,
  },
  {
    player: 'Rager_XL-9',
    kills: [1, 0, 0],
    placementPoints: [3, 15, 0],
    totalKills: 1,
    totalPlacementPoints: 18,
    killPoints: 3,
    finalPoints: 21,
  },
  {
    player: 'এKaizen',
    kills: [0, 0, 0],
    placementPoints: [15, 0, 5],
    totalKills: 0,
    totalPlacementPoints: 20,
    killPoints: 0,
    finalPoints: 20,
  },
  {
    player: 'Λp · Forgottenஜ',
    kills: [2, 2, 0],
    placementPoints: [3, 3, 0],
    totalKills: 4,
    totalPlacementPoints: 6,
    killPoints: 12,
    finalPoints: 18,
  },
  {
    player: 'siaka_aurq',
    kills: [0, 2, 0],
    placementPoints: [3, 3, 3],
    totalKills: 2,
    totalPlacementPoints: 9,
    killPoints: 6,
    finalPoints: 15,
  },
  {
    player: 'SiGMA來',
    kills: [1, 1, 1],
    placementPoints: [3, 3, 0],
    totalKills: 3,
    totalPlacementPoints: 6,
    killPoints: 9,
    finalPoints: 15,
  },
  {
    player: 'Λp · FROSTY',
    kills: [1, 2, 0],
    placementPoints: [3, 3, 0],
    totalKills: 3,
    totalPlacementPoints: 6,
    killPoints: 9,
    finalPoints: 15,
  },
  {
    player: "'FL°Captain",
    kills: [0, 0, 2],
    placementPoints: [0, 3, 3],
    totalKills: 2,
    totalPlacementPoints: 6,
    killPoints: 6,
    finalPoints: 12,
  },
  {
    player: 'Camp_Zazo',
    kills: [0, 2, 0],
    placementPoints: [0, 3, 3],
    totalKills: 2,
    totalPlacementPoints: 6,
    killPoints: 6,
    finalPoints: 12,
  },
  {
    player: 'Jâm_.âřî',
    kills: [1, 1, 0],
    placementPoints: [3, 3, 0],
    totalKills: 2,
    totalPlacementPoints: 6,
    killPoints: 6,
    finalPoints: 12,
  },
  {
    player: 'Λp · Kip',
    kills: [0, 0, 2],
    placementPoints: [0, 3, 3],
    totalKills: 2,
    totalPlacementPoints: 6,
    killPoints: 6,
    finalPoints: 12,
  },
  {
    player: 'Trim 來',
    kills: [0, 0, 3],
    placementPoints: [0, 0, 3],
    totalKills: 3,
    totalPlacementPoints: 3,
    killPoints: 9,
    finalPoints: 12,
  },
  {
    player: "Λ' Recoil",
    kills: [3, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 3,
    totalPlacementPoints: 3,
    killPoints: 9,
    finalPoints: 12,
  },
  {
    player: 'KiddMelloo',
    kills: [0, 0, 0],
    placementPoints: [3, 3, 3],
    totalKills: 0,
    totalPlacementPoints: 9,
    killPoints: 0,
    finalPoints: 9,
  },
  {
    player: 'Mr̃ Hèřϟ',
    kills: [0, 0, 0],
    placementPoints: [3, 3, 3],
    totalKills: 0,
    totalPlacementPoints: 9,
    killPoints: 0,
    finalPoints: 9,
  },
  {
    player: 'XSAura',
    kills: [0, 0, 1],
    placementPoints: [0, 3, 3],
    totalKills: 1,
    totalPlacementPoints: 6,
    killPoints: 3,
    finalPoints: 9,
  },
  {
    player: 'warhead2.0',
    kills: [1, 0, 0],
    placementPoints: [3, 3, 0],
    totalKills: 1,
    totalPlacementPoints: 6,
    killPoints: 3,
    finalPoints: 9,
  },
  {
    player: '暗裂®',
    kills: [0, 0, 1],
    placementPoints: [0, 3, 3],
    totalKills: 1,
    totalPlacementPoints: 6,
    killPoints: 3,
    finalPoints: 9,
  },
  {
    player: '4kVOID¥',
    kills: [0, 0, 0],
    placementPoints: [0, 3, 3],
    totalKills: 0,
    totalPlacementPoints: 6,
    killPoints: 0,
    finalPoints: 6,
  },
  {
    player: 'Ken_zo79',
    kills: [0, 0, 0],
    placementPoints: [0, 3, 3],
    totalKills: 0,
    totalPlacementPoints: 6,
    killPoints: 0,
    finalPoints: 6,
  },
  {
    player: 'cErea1_KIller',
    kills: [0, 0, 0],
    placementPoints: [0, 3, 3],
    totalKills: 0,
    totalPlacementPoints: 6,
    killPoints: 0,
    finalPoints: 6,
  },
  {
    player: '⬡Släyër⬡',
    kills: [0, 0, 0],
    placementPoints: [3, 3, 0],
    totalKills: 0,
    totalPlacementPoints: 6,
    killPoints: 0,
    finalPoints: 6,
  },
  {
    player: '2holine',
    kills: [1, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 1,
    totalPlacementPoints: 3,
    killPoints: 3,
    finalPoints: 6,
  },
  {
    player: 'WICKMANNN',
    kills: [1, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 1,
    totalPlacementPoints: 3,
    killPoints: 3,
    finalPoints: 6,
  },
  {
    player: 'danversaleks',
    kills: [0, 1, 0],
    placementPoints: [0, 0, 3],
    totalKills: 1,
    totalPlacementPoints: 3,
    killPoints: 3,
    finalPoints: 6,
  },
  {
    player: 'jean.ke',
    kills: [0, 0, 1],
    placementPoints: [0, 0, 3],
    totalKills: 1,
    totalPlacementPoints: 3,
    killPoints: 3,
    finalPoints: 6,
  },
  {
    player: 'niexy69',
    kills: [0, 0, 1],
    placementPoints: [0, 0, 3],
    totalKills: 1,
    totalPlacementPoints: 3,
    killPoints: 3,
    finalPoints: 6,
  },
  {
    player: 'rasakiki',
    kills: [1, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 1,
    totalPlacementPoints: 3,
    killPoints: 3,
    finalPoints: 6,
  },
  {
    player: '爪山Kavensetra',
    kills: [1, 0, 0],
    placementPoints: [0, 3, 0],
    totalKills: 1,
    totalPlacementPoints: 3,
    killPoints: 3,
    finalPoints: 6,
  },
  {
    player: 'Ash+ley2026',
    kills: [0, 0, 0],
    placementPoints: [0, 0, 3],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'HérสG๏๏dB๏y',
    kills: [0, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'Rurouni KE',
    kills: [0, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'Samuuo(11)',
    kills: [0, 0, 0],
    placementPoints: [0, 0, 3],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'glen20567',
    kills: [0, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'itsmemumo',
    kills: [0, 0, 0],
    placementPoints: [0, 3, 0],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'nelly_cool',
    kills: [0, 0, 0],
    placementPoints: [0, 0, 3],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'synchrophi',
    kills: [0, 0, 0],
    placementPoints: [0, 3, 0],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'xervelo',
    kills: [0, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: '愛VORTEX',
    kills: [0, 0, 0],
    placementPoints: [3, 0, 0],
    totalKills: 0,
    totalPlacementPoints: 3,
    killPoints: 0,
    finalPoints: 3,
  },
  {
    player: 'Fôxxy-22',
    kills: [0, 0, 0],
    placementPoints: [0, 0, 0],
    totalKills: 0,
    totalPlacementPoints: 0,
    killPoints: 0,
    finalPoints: 0,
  },
  {
    player: 'Spoiler626',
    kills: [0, 0, 0],
    placementPoints: [0, 0, 0],
    totalKills: 0,
    totalPlacementPoints: 0,
    killPoints: 0,
    finalPoints: 0,
  },
];
