// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/leaderboard" | "/lobbies" | "/lobbies/[id]" | "/login" | "/match/[id]" | "/profile" | "/queue" | "/register" | "/s/[username]" | "/s/match/[id]" | "/suggest"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/lobbies" | "/api/lobbies/[id]" | "/api/lobbies/[id]/join" | "/api/lobbies/[id]/leave" | "/api/matches/[id]" | "/api/matches/[id]/cancel" | "/api/matches/[id]/dispute" | "/api/matches/[id]/report" | "/api/matches/current" | "/api/matches/history" | "/api/matchmaking" | "/api/og/match" | "/api/og/profile" | "/api/queue/count/[game]" | "/api/queue/join" | "/api/queue/leave" | "/api/queue/status" | "/api/share/match/[id]" | "/api/share/profile/[username]" | "/api/suggestions" | "/api/suggestions/[id]/vote" | "/api/users/achievements" | "/api/users/leaderboard/[game]" | "/api/users/profile"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/lobbies": {}
  "/api/lobbies/[id]": { "id": string; }
  "/api/lobbies/[id]/join": { "id": string; }
  "/api/lobbies/[id]/leave": { "id": string; }
  "/api/matches/[id]": { "id": string; }
  "/api/matches/[id]/cancel": { "id": string; }
  "/api/matches/[id]/dispute": { "id": string; }
  "/api/matches/[id]/report": { "id": string; }
  "/api/matches/current": {}
  "/api/matches/history": {}
  "/api/matchmaking": {}
  "/api/og/match": {}
  "/api/og/profile": {}
  "/api/queue/count/[game]": { "game": string; }
  "/api/queue/join": {}
  "/api/queue/leave": {}
  "/api/queue/status": {}
  "/api/share/match/[id]": { "id": string; }
  "/api/share/profile/[username]": { "username": string; }
  "/api/suggestions": {}
  "/api/suggestions/[id]/vote": { "id": string; }
  "/api/users/achievements": {}
  "/api/users/leaderboard/[game]": { "game": string; }
  "/api/users/profile": {}
  "/dashboard": {}
  "/leaderboard": {}
  "/lobbies": {}
  "/lobbies/[id]": { "id": string; }
  "/login": {}
  "/match/[id]": { "id": string; }
  "/profile": {}
  "/queue": {}
  "/register": {}
  "/s/[username]": { "username": string; }
  "/s/match/[id]": { "id": string; }
  "/suggest": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
