// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/lobbies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lobbies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/lobbies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/lobbies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lobbies">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/lobbies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/match/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/match/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/match/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/queue">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/suggest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suggest">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/suggest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/s/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/s/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/s/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/s/match/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/s/match/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/s/match/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lobbies/[id]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies/[id]/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/lobbies/[id]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lobbies/[id]/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies/[id]/leave">> = Specific
  const handler = {} as typeof import("../../src/app/api/lobbies/[id]/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lobbies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/lobbies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lobbies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies">> = Specific
  const handler = {} as typeof import("../../src/app/api/lobbies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matches/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/matches/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matches/[id]/dispute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/dispute">> = Specific
  const handler = {} as typeof import("../../src/app/api/matches/[id]/dispute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matches/[id]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/matches/[id]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matches/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/matches/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matches/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/current">> = Specific
  const handler = {} as typeof import("../../src/app/api/matches/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matches/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/matches/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/matchmaking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matchmaking">> = Specific
  const handler = {} as typeof import("../../src/app/api/matchmaking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/match/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/match">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/match/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/profile/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/queue/count/[game]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/count/[game]">> = Specific
  const handler = {} as typeof import("../../src/app/api/queue/count/[game]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/queue/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/queue/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/queue/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/leave">> = Specific
  const handler = {} as typeof import("../../src/app/api/queue/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/queue/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/queue/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/share/match/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/match/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/share/match/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/share/profile/[username]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/profile/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/api/share/profile/[username]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/suggestions/[id]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggestions/[id]/vote">> = Specific
  const handler = {} as typeof import("../../src/app/api/suggestions/[id]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/achievements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/achievements">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/achievements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/leaderboard/[game]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/leaderboard/[game]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/leaderboard/[game]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
