var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/suggest/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kk7ta1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0y7nz-o.js")
R.c("server/chunks/ssr/[root-of-the-server]__006mmm2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ey7lm2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(app)_layout_tsx_0d~w2vh._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_suggest_page_actions_0i1_rhc.js")
R.m(19251)
module.exports=R.m(19251).exports
