'use client';
import { useCallback,useEffect,useState } from 'react'; import Link from 'next/link'; import { ArrowRight,CheckCircle2,Headphones,Plus,Send } from 'lucide-react'; import toast from 'react-hot-toast'; import { useAuth,useAuthFetch } from '@/components/AuthProvider'; import styles from './InAppSupport.module.css';
type SupportCase={id:string;subject:string;case_reference:string;status:string;last_message_at:string}; type Message={id:string;sender_type:string;body:string;created_at:string};
export function InAppSupport(){const {user,loading:authLoading}=useAuth();const authFetch=useAuthFetch();const [cases,setCases]=useState<SupportCase[]>([]);const [selected,setSelected]=useState<SupportCase|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [showForm,setShowForm]=useState(false);const [category,setCategory]=useState('tournament');const [subject,setSubject]=useState('');const [message,setMessage]=useState('');const [reply,setReply]=useState('');const [busy,setBusy]=useState(false);
const load=useCallback(async()=>{if(!user)return;const response=await authFetch('/api/support');if(response.ok){const payload=await response.json() as {cases?:SupportCase[]};setCases(payload.cases??[])}},[authFetch,user]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
async function openCase(item:SupportCase){setSelected(item);const response=await authFetch(`/api/support/${item.id}`);const payload=await response.json() as {messages?:Message[];error?:string};if(!response.ok)toast.error(payload.error||'Could not open this case.');else setMessages(payload.messages??[])}
async function createCase(event:React.FormEvent){event.preventDefault();setBusy(true);try{const response=await authFetch('/api/support',{method:'POST',body:JSON.stringify({category,subject,message,idempotency_key:crypto.randomUUID()})});const payload=await response.json() as {case?:SupportCase;error?:string};if(!response.ok||!payload.case)throw new Error(payload.error||'Could not create the case.');toast.success(`${payload.case.case_reference} created`);setShowForm(false);setSubject('');setMessage('');await load();await openCase(payload.case)}catch(error){toast.error(error instanceof Error?error.message:'Could not create the case.')}finally{setBusy(false)}}
async function sendReply(event:React.FormEvent){event.preventDefault();if(!selected)return;setBusy(true);try{const response=await authFetch(`/api/support/${selected.id}/messages`,{method:'POST',body:JSON.stringify({message:reply})});const payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||'Could not send the message.');setReply('');await openCase(selected);await load()}catch(error){toast.error(error instanceof Error?error.message:'Could not send the message.')}finally{setBusy(false)}}
if(authLoading)return null;if(!user)return <section className={styles.signin}><Headphones/><div><h2>Track help inside Mechi</h2><p>Sign in to open a private support case linked to your account.</p></div><Link href="/login?next=%2Fsupport">Sign in <ArrowRight size={15}/></Link></section>;
if(selected)return <section className={styles.case}><button className={styles.back} onClick={()=>setSelected(null)}>← All cases</button><header><div><small>{selected.case_reference}</small><h2>{selected.subject}</h2><p>{selected.status.replaceAll('_',' ')}</p></div></header><div className={styles.messages}>{messages.map(item=><article className={item.sender_type==='user'?styles.mine:styles.theirs} key={item.id}><strong>{item.sender_type==='user'?'You':'Mechi Support'}</strong><p>{item.body}</p></article>)}</div><form onSubmit={sendReply}><label>Reply<textarea required minLength={2} value={reply} onChange={event=>setReply(event.target.value)}/></label><button disabled={busy}><Send size={15}/>Send</button></form></section>;
return <section className={styles.wrap}><header><div><p>Private account support</p><h2>Your support cases</h2></div><button onClick={()=>setShowForm(value=>!value)}><Plus size={15}/>New case</button></header>{showForm?<form className={styles.form} onSubmit={createCase}><label>Topic<select value={category} onChange={event=>setCategory(event.target.value)}><option value="tournament">Tournament or registration</option><option value="payment">Payment or refund</option><option value="match_result">Match result</option><option value="team">Team</option><option value="account">Account access</option><option value="safety">Safety</option><option value="other">Something else</option></select></label><label>Subject<input required minLength={4} maxLength={120} value={subject} onChange={event=>setSubject(event.target.value)}/></label><label>What happened?<textarea required minLength={10} maxLength={5000} value={message} onChange={event=>setMessage(event.target.value)}/></label><button disabled={busy}>{busy?'Creating…':'Create support case'}</button></form>:null}<div className={styles.list}>{cases.length?cases.map(item=><button key={item.id} onClick={()=>void openCase(item)}><Headphones/><span><strong>{item.subject}</strong><small>{item.case_reference} · {item.status.replaceAll('_',' ')}</small></span><ArrowRight/></button>):<div className={styles.empty}><CheckCircle2/><strong>No open support history</strong><span>Create a case whenever you need help.</span></div>}</div></section>}
