import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ShieldCheck } from 'lucide-react';
import { BrandLogo } from '@/components/BrandLogo';
import { getPublicPassportReplay } from '@/lib/passport-progression';
import { APP_URL } from '@/lib/urls';

type Props = { params: Promise<{ token: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { token } = await params; const replay = await getPublicPassportReplay(token); if (!replay) return { title: 'Gamer Replay unavailable | Mechi V5' }; const title = `${replay.display_name}'s ${replay.replay_year} Gamer Replay`; const description = `${replay.payload.exact.games_added} games added, ${replay.payload.exact.verified_matches} verified matches, and ${replay.payload.exact.distinct_events} events on PlayMechi.`; return { title, description, openGraph: { title, description, images: [`${APP_URL}/api/passport/replay-cards/${token}`] }, twitter: { card: 'summary_large_image', title, description, images: [`${APP_URL}/api/passport/replay-cards/${token}`] } }; }
export default async function PublicReplayPage({ params }: Props) { const { token } = await params; const replay = await getPublicPassportReplay(token); if (!replay) notFound(); const exact = replay.payload.exact; return <main className="min-h-screen bg-[#071018] px-4 py-8 text-white"><div className="mx-auto max-w-5xl"><nav className="flex items-center justify-between"><BrandLogo size="sm"/><Link href={`/@${replay.username}`} className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">View Gamer Passport</Link></nav><section className="mt-8 overflow-hidden rounded-[2rem] border border-white/10 bg-[#0e1927]"><div className="relative aspect-[1200/630]"><Image src={`/api/passport/replay-cards/${token}`} alt={`${replay.replay_year} Gamer Replay`} fill priority unoptimized className="object-cover"/></div><div className="p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#32e0c4]">Transparent annual record</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{replay.display_name}&apos;s {replay.replay_year}</h1><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric value={exact.games_added} label="Games added"/><Metric value={exact.games_completed} label="Completed"/><Metric value={exact.verified_matches} label="Verified matches"/><Metric value={exact.distinct_events} label="Events attended"/><Metric value={exact.wins} label="Wins"/><Metric value={exact.teammates_played} label="Players faced"/><Metric value={exact.achievements_unlocked} label="Achievements"/><Metric value={exact.hours_recorded} label="Hours recorded"/></div><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.04] p-4 text-sm leading-6 text-white/65"><ShieldCheck className="mr-2 inline text-[#32e0c4]" size={16}/>Generated from {replay.payload.generated_from.join(', ')}. Source cutoff {new Date(replay.source_cutoff_at).toLocaleString()}. {replay.payload.estimates.length ? 'Any estimates are labeled individually.' : 'This Replay contains no estimated values.'}</div></div></section></div></main>; }
function Metric({ value, label }: { value: number; label: string }) { return <div className="rounded-2xl bg-white/[0.05] p-4"><p className="text-3xl font-black">{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-white/45">{label}</p></div>; }
