module.exports=[36132,a=>{a.v({className:"montserrat_fcee7c91-module__f3OsZW__className",variable:"montserrat_fcee7c91-module__f3OsZW__variable"})},77370,a=>{a.v({className:"open_sans_4d4845d1-module__-_tA7G__className",variable:"open_sans_4d4845d1-module__-_tA7G__variable"})},35929,a=>{"use strict";a.s(["AppProviders",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call AppProviders() from the server but AppProviders is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/src/components/AppProviders.tsx <module evaluation>","AppProviders")},48412,a=>{"use strict";a.s(["AppProviders",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call AppProviders() from the server but AppProviders is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/src/components/AppProviders.tsx","AppProviders")},2,a=>{"use strict";a.i(35929);var b=a.i(48412);a.n(b)},27572,a=>{"use strict";var b=a.i(7997),c=a.i(36132);let d={className:c.default.className,style:{fontFamily:"'Montserrat', 'Montserrat Fallback'",fontStyle:"normal"}};null!=c.default.variable&&(d.variable=c.default.variable);var e=a.i(77370);let f={className:e.default.className,style:{fontFamily:"'Open Sans', 'Open Sans Fallback'",fontStyle:"normal"}};null!=e.default.variable&&(f.variable=e.default.variable);var g=a.i(2);let h=`
  (() => {
    try {
      const root = document.documentElement;
      const storedTheme = localStorage.getItem('mechi-theme');
      const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
      const theme = storedTheme === 'light' || storedTheme === 'dark' ? storedTheme : systemTheme;
      root.classList.toggle('dark', theme === 'dark');
      root.dataset.theme = theme;
      root.style.colorScheme = theme;
    } catch {}
  })();
`;a.s(["default",0,function({children:a}){return(0,b.jsxs)("html",{lang:"en",className:`${d.variable} ${f.variable}`,suppressHydrationWarning:!0,children:[(0,b.jsx)("head",{children:(0,b.jsx)("script",{dangerouslySetInnerHTML:{__html:h}})}),(0,b.jsx)("body",{children:(0,b.jsx)(g.AppProviders,{children:a})})]})},"metadata",0,{title:"Mechi | Compete. Connect. Rise.",description:"Mechi is the competitive gaming platform for Kenyan players who want organized 1v1s, clean matchmaking, and a better way to rise.",keywords:["mechi","gaming","matchmaking","kenya","esports","1v1","competitive gaming","efootball","ea fc","tekken"],openGraph:{title:"Mechi | Compete. Connect. Rise.",description:"Organized 1v1 matchmaking for Kenyan players across football, fighters, sports, and mobile competition.",url:"https://mechi.club",siteName:"Mechi",locale:"en_KE",type:"website"},twitter:{card:"summary_large_image",title:"Mechi | Compete. Connect. Rise.",description:"Organized 1v1 matchmaking for Kenyan players who want better competition and cleaner progression."}},"viewport",0,{width:"device-width",initialScale:1,themeColor:[{media:"(prefers-color-scheme: light)",color:"#f8fbfd"},{media:"(prefers-color-scheme: dark)",color:"#0B1121"}]}],27572)},50645,a=>{a.n(a.i(27572))}];

//# sourceMappingURL=%5Broot-of-the-server%5D__0ey7lm2._.js.map