'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, EyeOff, Link2, RefreshCw, RotateCcw, ShieldCheck, Trash2, Unplug } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuthFetch } from '@/components/AuthProvider';
import type { PassportExternalItem, PassportProviderConnection, PassportProviderDefinition } from '@/lib/passport-connections-types';

type Rollout = { enabled: boolean; rollout_percent: number; reason: string | null };
type Hub = { providers: PassportProviderDefinition[]; connections: PassportProviderConnection[]; items: PassportExternalItem[]; storage_ready: boolean; rollout: Rollout };
export function PassportConnectionsManager({ initialNotice, initialError }: { initialNotice: string | null; initialError: string | null }) {
  const authFetch = useAuthFetch(); const [hub, setHub] = useState<Hub | null>(null); const [working, setWorking] = useState(''); const [visibility, setVisibility] = useState<'public' | 'friends' | 'private'>('private');
  const load = useCallback(async () => { const response = await authFetch('/api/passport/connections'); const payload = await response.json(); if (!response.ok) toast.error(payload.error ?? 'Could not load platform connections'); else setHub(payload); }, [authFetch]);
  useEffect(() => { if (initialNotice) toast.success(initialNotice); if (initialError) toast.error(initialError); const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [initialError, initialNotice, load]);
  const byProvider = useMemo(() => new Map(hub?.connections.map((connection) => [connection.provider_key, connection]) ?? []), [hub]);
  async function syncSteam() { setWorking('sync'); const response = await authFetch('/api/passport/connections/steam/sync', { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() } }); const payload = await response.json(); setWorking(''); if (!response.ok) return toast.error(payload.error ?? 'Steam sync failed'); toast.success(`Steam reconciled: ${payload.fetched ?? 0} games found, ${payload.staged ?? 0} new`); await load(); }
  async function review(item: PassportExternalItem, action: 'accept' | 'hide' | 'restore') { setWorking(item.id); const response = await authFetch(`/api/passport/imports/${item.id}`, { method: 'PATCH', body: JSON.stringify({ action, visibility }) }); const payload = await response.json(); setWorking(''); if (!response.ok) return toast.error(payload.error ?? 'Could not update import'); toast.success(action === 'accept' ? `${item.title} added without overwriting personal notes` : action === 'hide' ? `${item.title} hidden from import review` : `${item.title} restored`); await load(); }
  async function disconnect(erase: boolean) { if (erase && !window.confirm('Erase Steam sync data? Imported games with personal notes will be converted to manual entries; untouched synced-only entries will be removed.')) return; setWorking(erase ? 'erase' : 'disconnect'); const response = await authFetch('/api/passport/connections', { method: 'DELETE', body: JSON.stringify({ provider: 'steam', erase_provider_data: erase }) }); const payload = await response.json(); setWorking(''); if (!response.ok) return toast.error(payload.error ?? 'Could not disconnect Steam'); toast.success(erase ? 'Steam provider data erased safely' : 'Steam disconnected; existing imported Passport entries remain'); await load(); }
  if (!hub) return <main className="mx-auto max-w-6xl px-4 py-10 text-sm text-[var(--text-soft)]">Loading connection controls…</main>;
  const steam = byProvider.get('steam'); const staged = hub.items.filter((item) => item.import_state === 'staged' || item.import_state === 'conflict'); const imported = hub.items.filter((item) => item.import_state === 'imported'); const hidden = hub.items.filter((item) => item.import_state === 'hidden');
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-7 sm:px-7"><header className="card p-6 sm:p-8"><p className="brand-kicker">Phase 8 · controlled rollout</p><h1 className="mt-3 text-3xl font-black text-[var(--text-primary)] sm:text-4xl">Connect accounts without surrendering your Passport</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]">A provider proves ownership and supplies attributed facts. Nothing enters your public library until you review it. Provider outages never remove your core Mechi identity, notes, matches, events, or manual games.</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold text-[var(--text-soft)]"><span className="rounded-full bg-black/10 px-3 py-2">Explicit consent</span><span className="rounded-full bg-black/10 px-3 py-2">Granular scopes</span><span className="rounded-full bg-black/10 px-3 py-2">Idempotent imports</span><span className="rounded-full bg-black/10 px-3 py-2">Disconnect and erase</span></div></header>
    {!hub.rollout.enabled ? <section className="rounded-3xl border border-amber-400/30 bg-amber-400/10 p-5"><p className="font-black text-amber-600">Connections are in a controlled rollout</p><p className="mt-2 text-sm text-[var(--text-secondary)]">{hub.rollout.reason}. Existing connections can still be disconnected or erased safely.</p></section> : null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{hub.providers.map((provider) => { const connection = byProvider.get(provider.key); const available = provider.status === 'available' && hub.rollout.enabled; return <article key={provider.key} className="card p-5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--brand-teal)]/10 text-[var(--brand-teal)]"><Link2 size={20}/></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${connection && connection.status !== 'revoked' ? 'bg-emerald-400/10 text-emerald-500' : available ? 'bg-[var(--brand-teal)]/10 text-[var(--brand-teal)]' : 'bg-black/10 text-[var(--text-soft)]'}`}>{connection && connection.status !== 'revoked' ? connection.status : provider.status}</span></div><h2 className="mt-4 text-xl font-black text-[var(--text-primary)]">{provider.label}</h2><p className="mt-2 text-xs leading-5 text-[var(--text-soft)]">{provider.capability_scopes.map((scope) => scope.replace(':read', '').replaceAll('_', ' ')).join(' · ')}</p>{connection && connection.status !== 'revoked' ? <div className="mt-4 rounded-2xl bg-black/10 p-3"><p className="font-black text-[var(--text-primary)]">{connection.account_label}</p><p className="mt-1 text-xs text-[var(--text-soft)]">Last sync: {connection.last_synced_at ? new Date(connection.last_synced_at).toLocaleString() : 'Never'} · {connection.last_sync_status}</p>{connection.last_error_message ? <p className="mt-2 text-xs text-amber-500">{connection.last_error_message}</p> : null}</div> : available ? <a href={`/api/passport/connections/${provider.key}/start?return=/passport/connections`} className="btn-primary mt-4 inline-flex items-center gap-2"><ShieldCheck size={16}/>Verify ownership</a> : <p className="mt-4 text-sm text-[var(--text-soft)]">{provider.status === 'available' ? 'Currently outside your rollout cohort.' : 'Planned only. Mechi will not offer unofficial or password-based linking.'}</p>}{provider.terms_url && provider.privacy_url ? <p className="mt-4 text-[10px] text-[var(--text-soft)]"><a href={provider.terms_url} target="_blank" rel="noreferrer">Provider terms</a> · <a href={provider.privacy_url} target="_blank" rel="noreferrer">Privacy</a></p> : null}</article>; })}</section>
    {steam && steam.status !== 'revoked' ? <section className="card p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="brand-kicker">Steam library reconciliation</p><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">Review before importing</h2><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Steam must allow game details to be visible. Sync stages owned titles and recorded playtime; it does not publish them or infer completion.</p></div><div className="flex flex-wrap gap-2"><button disabled={Boolean(working) || !hub.rollout.enabled} onClick={() => void syncSteam()} className="btn-primary inline-flex items-center gap-2"><RefreshCw size={16}/>{working === 'sync' ? 'Syncing…' : 'Sync Steam'}</button><button disabled={Boolean(working)} onClick={() => void disconnect(false)} className="btn-outline inline-flex items-center gap-2"><Unplug size={15}/>Disconnect</button><button disabled={Boolean(working)} onClick={() => void disconnect(true)} className="btn-ghost inline-flex items-center gap-2 text-rose-500"><Trash2 size={15}/>Erase data</button></div></div><label className="mt-5 block max-w-xs"><span className="label">Visibility for newly accepted games</span><select className="input-field mt-2" value={visibility} onChange={(event) => setVisibility(event.target.value as typeof visibility)}><option value="private">Only me</option><option value="friends">Friends</option><option value="public">Public</option></select></label></section> : null}
    <section className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><div className="card p-6"><div className="flex items-center justify-between"><div><p className="brand-kicker">Import inbox</p><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">{staged.length} titles waiting</h2></div><span className="text-xs text-[var(--text-soft)]">{imported.length} imported</span></div><div className="mt-5 max-h-[38rem] space-y-2 overflow-auto">{staged.map((item) => <article key={item.id} className="flex flex-col gap-3 rounded-2xl border border-[var(--border)] p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><h3 className="truncate font-black text-[var(--text-primary)]">{item.title}</h3><p className="mt-1 text-xs text-[var(--text-soft)]">Steam · {Math.round((item.safe_details.playtime_hours ?? 0) * 10) / 10} hours recorded · not yet on Passport</p></div><div className="flex gap-2"><button disabled={Boolean(working)} onClick={() => void review(item, 'accept')} className="btn-primary inline-flex items-center gap-1"><Check size={14}/>Accept</button><button disabled={Boolean(working)} onClick={() => void review(item, 'hide')} className="btn-ghost inline-flex items-center gap-1"><EyeOff size={14}/>Hide</button></div></article>)}{!staged.length ? <p className="rounded-2xl border border-dashed border-[var(--border)] p-8 text-center text-sm text-[var(--text-soft)]">No staged titles. Sync Steam when you want to reconcile its current visible library.</p> : null}</div></div><aside className="space-y-5"><section className="card p-5"><h2 className="font-black text-[var(--text-primary)]">Conflict policy</h2><ul className="mt-3 space-y-2 text-xs leading-5 text-[var(--text-soft)]"><li>• Personal notes, rating, status, favorites, screenshots, and visibility always survive.</li><li>• Recorded hours use the higher accepted value.</li><li>• Steam never marks a story game completed.</li><li>• Removed Steam games do not silently delete Passport history.</li></ul></section>{hidden.length ? <section className="card p-5"><h2 className="font-black text-[var(--text-primary)]">Hidden imports</h2><div className="mt-3 space-y-2">{hidden.slice(0, 20).map((item) => <button key={item.id} onClick={() => void review(item, 'restore')} className="flex w-full items-center justify-between rounded-xl bg-black/10 p-3 text-left text-sm font-bold text-[var(--text-primary)]"><span className="truncate">{item.title}</span><RotateCcw size={14}/></button>)}</div></section> : null}</aside></section>
  </main>;
}
