'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Eye, LockKeyhole, Save, ShieldCheck, Sparkles, Star, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuthFetch } from '@/components/AuthProvider';
import type { PassportProgression } from '@/lib/passport-progression-types';

type ShowcaseSource = { source_type: string; source_id: string; label: string };
type Shelf = { id: string; title: string; description: string; visibility: string; items: unknown[] };
type GameOption = { id: string; game: { title?: string } | Array<{ title?: string }> | null };
function gameTitle(game: GameOption['game']) { return (Array.isArray(game) ? game[0]?.title : game?.title) ?? 'Game'; }

export function PassportCustomizationStudio() {
  const authFetch = useAuthFetch();
  const [progression, setProgression] = useState<PassportProgression | null>(null);
  const [sources, setSources] = useState<ShowcaseSource[]>([]);
  const [shelves, setShelves] = useState<Shelf[]>([]);
  const [games, setGames] = useState<GameOption[]>([]);
  const [theme, setTheme] = useState('mechi_core'); const [frame, setFrame] = useState('frame_none'); const [card, setCard] = useState('card_core');
  const [showDimensions, setShowDimensions] = useState(true); const [showLevel, setShowLevel] = useState(true);
  const [sourceKey, setSourceKey] = useState(''); const [slot, setSlot] = useState(1); const [visibility, setVisibility] = useState('public');
  const [shelfTitle, setShelfTitle] = useState(''); const [shelfDescription, setShelfDescription] = useState(''); const [selectedGames, setSelectedGames] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const [customResponse, showcaseResponse, shelvesResponse] = await Promise.all([authFetch('/api/passport/customization'), authFetch('/api/passport/showcase'), authFetch('/api/passport/shelves')]); const [customPayload, showcasePayload, shelvesPayload] = await Promise.all([customResponse.json(), showcaseResponse.json(), shelvesResponse.json()]); if (!customResponse.ok) toast.error(customPayload.error ?? 'Could not load customization'); else { const value = customPayload.progression as PassportProgression; setProgression(value); setTheme(value.customization.theme_key); setFrame(value.customization.avatar_frame_key); setCard(value.customization.card_style_key); setShowDimensions(value.customization.show_dimensions); setShowLevel(value.customization.show_level); } if (showcaseResponse.ok) setSources(showcasePayload.sources ?? []); if (shelvesResponse.ok) { setShelves(shelvesPayload.shelves ?? []); setGames(shelvesPayload.games ?? []); } }, [authFetch]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const grouped = useMemo(() => ({ theme: progression?.cosmetics.filter((item) => item.type === 'theme') ?? [], avatar_frame: progression?.cosmetics.filter((item) => item.type === 'avatar_frame') ?? [], card_style: progression?.cosmetics.filter((item) => item.type === 'card_style') ?? [] }), [progression]);

  async function saveCustomization() { setSaving(true); const response = await authFetch('/api/passport/customization', { method: 'PATCH', body: JSON.stringify({ theme_key: theme, avatar_frame_key: frame, card_style_key: card, show_dimensions: showDimensions, show_level: showLevel }) }); const payload = await response.json(); setSaving(false); if (!response.ok) return toast.error(payload.error ?? 'Could not save customization'); toast.success('Passport style saved'); await load(); }
  async function addShowcase(event: React.FormEvent) { event.preventDefault(); const source = sources.find((item) => `${item.source_type}:${item.source_id}` === sourceKey); if (!source) return toast.error('Choose a source'); const response = await authFetch('/api/passport/showcase', { method: 'POST', body: JSON.stringify({ slot, source_type: source.source_type, source_id: source.source_id, label: source.label, visibility }) }); const payload = await response.json(); if (!response.ok) return toast.error(payload.error ?? 'Could not add showcase item'); toast.success('Showcase updated'); await load(); }
  async function removeShowcase(id: string) { const response = await authFetch('/api/passport/showcase', { method: 'DELETE', body: JSON.stringify({ id }) }); if (!response.ok) return toast.error('Could not remove item'); await load(); }
  async function addShelf(event: React.FormEvent) { event.preventDefault(); const response = await authFetch('/api/passport/shelves', { method: 'POST', body: JSON.stringify({ title: shelfTitle, description: shelfDescription, visibility, display_order: shelves.length, game_entry_ids: selectedGames }) }); const payload = await response.json(); if (!response.ok) return toast.error(payload.error ?? 'Could not save shelf'); toast.success('Custom shelf created'); setShelfTitle(''); setShelfDescription(''); setSelectedGames([]); await load(); }

  if (!progression) return <main className="mx-auto max-w-6xl px-4 py-10 text-sm text-[var(--text-soft)]">Loading Passport Studio…</main>;
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-7 sm:px-7"><header className="card p-6 sm:p-8"><p className="brand-kicker">Passport Studio</p><h1 className="mt-3 text-3xl font-black text-[var(--text-primary)]">Make your Passport feel like yours</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]">Themes, frames, and card treatments are always marked as cosmetic. Verification, achievements, match results, and event credentials cannot be purchased.</p><p className="mt-4 inline-flex items-center gap-2 rounded-full bg-[var(--brand-teal)]/10 px-3 py-2 text-xs font-black uppercase text-[var(--brand-teal)]"><ShieldCheck size={14}/>{progression.customization.plan} plan · {progression.customization.showcase_limit} showcase slots</p></header>
    <section className="card p-6"><div className="flex items-end justify-between gap-4"><div><p className="brand-kicker">Cosmetic identity</p><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">Style controls</h2></div><button onClick={() => void saveCustomization()} disabled={saving} className="btn-primary inline-flex items-center gap-2"><Save size={16}/>{saving ? 'Saving…' : 'Save style'}</button></div><div className="mt-6 grid gap-5 lg:grid-cols-3">{([{ label: 'Theme', key: 'theme', value: theme, set: setTheme }, { label: 'Avatar frame', key: 'avatar_frame', value: frame, set: setFrame }, { label: 'Gamer Card', key: 'card_style', value: card, set: setCard }] as const).map((group) => <fieldset key={group.key}><legend className="label">{group.label}</legend><div className="mt-2 space-y-2">{grouped[group.key].map((item) => <label key={item.key} className={`flex cursor-pointer gap-3 rounded-2xl border p-3 ${group.value === item.key ? 'border-[var(--brand-teal)] bg-[var(--brand-teal)]/10' : 'border-[var(--border)]'}`}><input type="radio" name={group.key} value={item.key} checked={group.value === item.key} disabled={!item.unlocked} onChange={() => group.set(item.key)} /><span><span className="flex items-center gap-2 font-black text-[var(--text-primary)]">{item.label}{!item.unlocked ? <LockKeyhole size={13}/> : null}</span><span className="mt-1 block text-xs text-[var(--text-soft)]">{item.description} · {item.required_plan}{item.is_animated ? ' · motion-safe animation' : ''}</span></span></label>)}</div></fieldset>)}</div><div className="mt-5 flex flex-wrap gap-5"><label className="flex items-center gap-2 text-sm font-bold text-[var(--text-secondary)]"><input type="checkbox" checked={showDimensions} onChange={(event) => setShowDimensions(event.target.checked)}/>Show Gamer Dimensions</label><label className="flex items-center gap-2 text-sm font-bold text-[var(--text-secondary)]"><input type="checkbox" checked={showLevel} onChange={(event) => setShowLevel(event.target.checked)}/>Show Passport Level</label></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><form onSubmit={addShowcase} className="card p-6"><p className="brand-kicker">Tangible profile</p><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">Curated showcase</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Pin source-backed games, achievements, credentials, and moments to numbered slots.</p><select required className="input-field mt-5" value={sourceKey} onChange={(event) => setSourceKey(event.target.value)}><option value="">Choose a source</option>{sources.map((source) => <option key={`${source.source_type}:${source.source_id}`} value={`${source.source_type}:${source.source_id}`}>{source.label}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-3"><input className="input-field" type="number" min={1} max={progression.customization.showcase_limit} value={slot} onChange={(event) => setSlot(Number(event.target.value))}/><select className="input-field" value={visibility} onChange={(event) => setVisibility(event.target.value)}><option value="public">Public</option><option value="friends">Friends</option><option value="private">Only me</option></select></div><button className="btn-primary mt-4 inline-flex items-center gap-2"><Star size={16}/>Place in showcase</button><div className="mt-5 space-y-2">{progression.showcase.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-[var(--border)] p-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-black/10 text-xs font-black">{item.slot}</span><span className="min-w-0 flex-1 truncate text-sm font-bold text-[var(--text-primary)]">{item.label}</span><span className="text-[10px] uppercase text-[var(--text-soft)]">{item.visibility}</span><button type="button" aria-label={`Remove ${item.label}`} onClick={() => void removeShowcase(item.id)}><Trash2 size={15}/></button></div>)}</div></form>
      <form onSubmit={addShelf} className="card p-6"><p className="brand-kicker">Pro collection tool</p><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">Custom game shelves</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Build named collections such as “Story worlds I finished” or “Squad-night rotation.” Core library visibility remains free.</p><input className="input-field mt-5" required minLength={2} maxLength={60} placeholder="Shelf title" value={shelfTitle} onChange={(event) => setShelfTitle(event.target.value)}/><textarea className="input-field mt-3" maxLength={180} placeholder="What connects these games?" value={shelfDescription} onChange={(event) => setShelfDescription(event.target.value)}/><div className="mt-3 max-h-40 space-y-2 overflow-auto rounded-2xl border border-[var(--border)] p-3">{games.map((game) => <label key={game.id} className="flex items-center gap-2 text-sm text-[var(--text-secondary)]"><input type="checkbox" checked={selectedGames.includes(game.id)} onChange={(event) => setSelectedGames((current) => event.target.checked ? [...current, game.id] : current.filter((id) => id !== game.id))}/>{gameTitle(game.game)}</label>)}</div><button className="btn-outline mt-4 inline-flex items-center gap-2"><Sparkles size={16}/>Create shelf</button><div className="mt-5 grid gap-2">{shelves.map((shelf) => <div key={shelf.id} className="rounded-xl bg-black/10 p-3"><p className="font-black text-[var(--text-primary)]">{shelf.title}</p><p className="mt-1 text-xs text-[var(--text-soft)]">{shelf.description || `${shelf.items?.length ?? 0} games`} · {shelf.visibility}</p></div>)}</div></form></section>
    <p className="flex items-center gap-2 px-2 text-xs text-[var(--text-soft)]"><Eye size={14}/>Animations respect reduced-motion preferences and remain within light/moderate performance tiers.</p>
  </main>;
}
