'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { Award, ChevronRight, Compass, Gamepad2, ShieldCheck, Sparkles, Swords, Trophy, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuthFetch } from '@/components/AuthProvider';
import type { GamerDimensionKey, PassportProgression } from '@/lib/passport-progression-types';

const ICONS: Record<GamerDimensionKey, typeof Swords> = { competitive: Swords, explorer: Compass, completionist: Trophy, community: Users, event_presence: Sparkles, team_player: ShieldCheck };
const TRUST = { personal: 'Owner recorded', mechi_verified: 'Mechi verified', organizer_verified: 'Organizer verified' } as const;

export function PassportProgressionDashboard() {
  const authFetch = useAuthFetch();
  const [data, setData] = useState<PassportProgression | null>(null);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { const response = await authFetch('/api/passport/progression'); const payload = await response.json(); if (!response.ok) toast.error(payload.error ?? 'Could not load progression'); else setData(payload.progression); setLoading(false); }, [authFetch]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  if (loading) return <main className="mx-auto max-w-6xl px-4 py-10 text-sm text-[var(--text-soft)]">Calculating your Gamer Dimensions…</main>;
  if (!data) return <main className="mx-auto max-w-6xl px-4 py-10">Progression is unavailable.</main>;

  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-7 sm:px-7">
    <header className="card overflow-hidden p-6 sm:p-8">
      <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="brand-kicker">Mechi V5 progression</p><h1 className="mt-3 text-3xl font-black text-[var(--text-primary)] sm:text-4xl">Your gaming identity, in six dimensions</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]">No single score can decide who the “best gamer” is. Your Passport Level reflects breadth of participation; each Dimension stays independent and explains exactly what contributed.</p></div><div className="rounded-3xl border border-[var(--brand-teal)]/25 bg-[var(--brand-teal)]/10 p-5 text-center"><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--brand-teal)]">Passport level</p><p className="mt-1 text-5xl font-black text-[var(--text-primary)]">{data.passport_level}</p><p className="mt-1 text-xs text-[var(--text-soft)]">{data.total_points} / 600 dimension points</p></div></div>
      <div className="mt-5 flex flex-wrap gap-2"><Link className="btn-primary inline-flex items-center gap-2" href="/passport/customize"><Sparkles size={16}/>Customize Passport</Link><Link className="btn-outline inline-flex items-center gap-2" href="/passport/replay">Build Annual Replay<ChevronRight size={16}/></Link></div>
    </header>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.dimensions.map((dimension) => { const Icon = ICONS[dimension.key]; return <article key={dimension.key} className="card p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[var(--brand-teal)]/10 text-[var(--brand-teal)]"><Icon size={19}/></span><span className="text-2xl font-black text-[var(--text-primary)]">{dimension.score}<span className="text-xs text-[var(--text-soft)]">/100</span></span></div><h2 className="mt-4 text-lg font-black text-[var(--text-primary)]">{dimension.label}</h2><p className="mt-1 text-xs font-bold uppercase tracking-wider text-[var(--brand-teal)]">{dimension.level}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-black/15"><div className="h-full rounded-full bg-[var(--brand-teal)]" style={{ width: `${dimension.score}%` }}/></div><p className="mt-4 text-sm leading-6 text-[var(--text-secondary)]">{dimension.explanation}</p><dl className="mt-4 grid grid-cols-2 gap-2">{dimension.inputs.map((input) => <div key={input.label} className="rounded-xl bg-black/10 p-3"><dt className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-soft)]">{input.label}</dt><dd className="mt-1 font-black text-[var(--text-primary)]">{input.value}</dd></div>)}</dl></article>; })}</section>
    <section className="card p-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="brand-kicker">Achievement cabinet</p><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">Earned from traceable sources</h2></div><p className="max-w-xl text-xs leading-5 text-[var(--text-soft)]">Requirements, issuer, date, rarity, and trust source remain visible. Revoked sources remove the active award; paid cosmetics never imitate verification.</p></div><div className="mt-5 grid gap-3 md:grid-cols-2">{data.achievements.filter((achievement) => achievement.is_active).map((achievement) => <article key={`${achievement.key}:${achievement.issued_at}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-raised)] p-4"><div className="flex items-start gap-3"><Award className="mt-1 shrink-0 text-[var(--brand-gold)]" size={20}/><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-[var(--text-primary)]">{achievement.title}</h3><span className="rounded-full bg-black/10 px-2 py-1 text-[10px] font-black uppercase tracking-wide text-[var(--text-soft)]">{achievement.rarity}</span></div><p className="mt-2 text-sm text-[var(--text-secondary)]">{achievement.description}</p><p className="mt-3 text-xs text-[var(--text-soft)]">Requirement: {achievement.requirement}</p><p className="mt-1 inline-flex items-center gap-1 text-xs font-bold text-[var(--brand-teal)]"><ShieldCheck size={13}/>{TRUST[achievement.trust_tier]} · {achievement.issuer}</p></div></div></article>)}{!data.achievements.some((achievement) => achievement.is_active) ? <div className="rounded-2xl border border-dashed border-[var(--border)] p-8 text-center text-sm text-[var(--text-soft)]"><Gamepad2 className="mx-auto mb-3"/>Add games, finish titles, compete, attend events, and join teams to begin your cabinet.</div> : null}</div></section>
    <p className="px-2 text-xs leading-5 text-[var(--text-soft)]">Formula {data.formula_version}. {data.level_explanation} Calculated {new Date(data.projected_at).toLocaleString()}.</p>
  </main>;
}
