'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowLeft, ArrowRight, CalendarClock, CheckCircle2, CircleAlert, Gamepad2, ShieldCheck, Trophy, UsersRound, WalletCards } from 'lucide-react';
import { useAuth, useAuthFetch } from '@/components/AuthProvider';
import styles from './V5PlayerTournamentFlow.module.css';

export type PlayerTournament = { id:string;slug:string;title:string;game?:string|null;platform?:string|null;region?:string|null;status?:string|null;scheduled_for?:string|null;size?:number|null;player_count?:number|null;entry_fee?:number|null;prize_pool?:number|null;approval_status?:string|null;participant_type?:'solo'|'team'|null;team_size?:number|null;valuable_reward_exists?:boolean|null;reward_description?:string|null };

export function V5PlayerTournamentFlow({ tournaments,loading }: { tournaments:PlayerTournament[];loading:boolean }) {
  const search=useSearchParams(); const slug=search.get('join'); const reference=search.get('reference');
  const tournament=slug?tournaments.find((item)=>item.slug===slug):null;
  if(slug) return <Registration tournament={tournament||null} loading={loading} reference={reference}/>;
  return <Directory tournaments={tournaments} loading={loading}/>;
}

function Registration({tournament,loading,reference}:{tournament:PlayerTournament|null;loading:boolean;reference:string|null}){
  const {user}=useAuth(); const authFetch=useAuthFetch(); const [state,setState]=useState<'ready'|'joining'|'verifying'|'joined'|'error'>(reference?'verifying':'ready'); const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{if(!reference||!tournament)return;let mounted=true;void authFetch(`/api/tournaments/${encodeURIComponent(tournament.slug)}/verify-payment`,{method:'POST',body:JSON.stringify({reference})}).then(async(response)=>({ok:response.ok,payload:await response.json().catch(()=>null)})).then(({ok,payload})=>{if(!mounted)return;if(ok){setState('joined');setMessage('Payment confirmed. Your tournament entry is locked in.');}else{setState('error');setMessage(payload?.error||'Payment is not confirmed yet. You can retry verification safely.');}}).catch(()=>{if(mounted){setState('error');setMessage('Payment verification was interrupted. Your reference is safe; retry when connected.');}});return()=>{mounted=false};},[authFetch,reference,tournament]);
  if(loading)return <div className={styles.loading}><span/><span/><span/></div>;
  if(!tournament)return <div className={styles.missing}><CircleAlert/><h1>Tournament unavailable</h1><p>It may no longer be public, or the link may be incomplete.</p><Link href="/app/player/tournaments"><ArrowLeft size={16}/> Back to tournaments</Link></div>;
  const tournamentSlug=tournament.slug;
  const gameConnected=user?.selected_games?.some((game)=>game===tournament.game||game==='efootball_mobile'&&tournament.game==='efootball'); const open=tournament.status==='open'; const approved=!tournament.approval_status||tournament.approval_status==='approved'; const team=tournament.participant_type==='team'; const eligible=Boolean(gameConnected&&open&&approved&&!team);
  async function join(){setState('joining');setMessage(null);try{const response=await authFetch(`/api/tournaments/${encodeURIComponent(tournamentSlug)}/join`,{method:'POST'});const payload=await response.json().catch(()=>null);if(!response.ok){setState('error');setMessage(payload?.error||'Your entry could not be completed.');return}if(payload?.status==='payment_pending'&&payload.authorization_url){window.location.assign(payload.authorization_url);return}setState('joined');setMessage('You are registered. Schedule and check-in actions will stay in this dashboard.');}catch{setState('error');setMessage('Connection interrupted. Check this dashboard before retrying to avoid duplicate action.')}}
  return <div className={styles.page}><header className={styles.heading}><div><Link href="/app/player/tournaments"><ArrowLeft size={15}/> Tournaments</Link><p>Player registration</p><h1>{tournament.title}</h1><span>Review eligibility and entry terms before reserving your place.</span></div><span className={open?styles.open:styles.closed}>{open?'Registration open':tournament.status||'Unavailable'}</span></header>
    {message?<div className={state==='joined'?styles.success:styles.error} role="status">{state==='joined'?<CheckCircle2/>:<CircleAlert/>}<div><strong>{state==='joined'?'Entry confirmed':'Action needs attention'}</strong><span>{message}</span></div></div>:null}
    <div className={styles.metrics}><Metric icon={<Gamepad2/>} label="Game & platform" value={format(tournament.game)} note={format(tournament.platform)}/><Metric icon={<UsersRound/>} label="Format" value={team?`${tournament.team_size||'—'} per team`:'Solo'} note={`${tournament.player_count||0}/${tournament.size||'—'} entries`}/><Metric icon={<WalletCards/>} label="Entry" value={tournament.entry_fee?`KES ${number(tournament.entry_fee)}`:'Free'} note={tournament.prize_pool?`KES ${number(tournament.prize_pool)} cash prize`:'No cash prize'}/><Metric icon={<CalendarClock/>} label="Schedule" value={date(tournament.scheduled_for)} note="East Africa Time"/></div>
    <div className={styles.columns}><section className={styles.panel}><div className={styles.panelHeading}><h2>Eligibility check</h2><span>Account-specific</span></div><div className={styles.checks}><Check label="Registration is open" complete={open} help={open?'This event accepts entries.':'The organizer has closed entry.'}/><Check label={`${format(tournament.game)} is connected`} complete={Boolean(gameConnected)} help={gameConnected?'Your competition identity includes this game.':'Add the game in Player Profile before joining.'}/><Check label="Tournament is approved for entry" complete={approved} help={approved?'Policy gate cleared.':'Registration remains closed during Mechi review.'}/><Check label={team?'Eligible team selected':'Solo entry selected'} complete={!team} help={team?'Team events are entered by a captain from the Team Dashboard.':'This tournament accepts individual players.'}/></div>{team?<Link className={styles.primary} href={`/app/team/tournaments?join=${encodeURIComponent(tournament.slug)}`}>Continue in Team Dashboard <ArrowRight size={16}/></Link>:state==='joined'?<Link className={styles.primary} href="/app/player">Return to Player Dashboard <ArrowRight size={16}/></Link>:<button className={styles.primary} type="button" disabled={!eligible||state==='joining'||state==='verifying'} onClick={join}>{state==='joining'?'Reserving entry…':state==='verifying'?'Verifying payment…':tournament.entry_fee?'Continue to Paystack':'Confirm free entry'} <ArrowRight size={16}/></button>} {!eligible&&!team?<p className={styles.blockedCopy}>Resolve the incomplete eligibility item above. No payment or entry is created while blocked.</p>:null}</section>
      <aside className={styles.panel}><div className={styles.panelHeading}><h2>What happens next</h2></div><ol className={styles.steps}><li><span>1</span><div><strong>{tournament.entry_fee?'Secure Paystack payment':'Entry confirmation'}</strong><small>{tournament.entry_fee?'Your slot is reserved while payment is active.':'No payment is required for this event.'}</small></div></li><li><span>2</span><div><strong>Check-in opens</strong><small>The dashboard shows the time, roster rules and next owner.</small></div></li><li><span>3</span><div><strong>Match workspace</strong><small>Communication, result, evidence and dispute stay attached to the match.</small></div></li></ol><div className={styles.trust}><ShieldCheck/><span><strong>Credible competition trail</strong><small>Entry, payment reference, result and decisions remain auditable.</small></span></div><Link className={styles.publicLink} href={`/tournaments/${encodeURIComponent(tournament.slug)}`}>Review public tournament page</Link></aside></div>
  </div>;
}

function Directory({tournaments,loading}:{tournaments:PlayerTournament[];loading:boolean}){return <div className={styles.page}><header className={styles.heading}><div><p>Player workspace</p><h1>Your tournaments</h1><span>Discover public events, continue registration and return to active competition from one workspace.</span></div><Link className={styles.headerAction} href="/tournaments">Browse public directory <ArrowRight size={16}/></Link></header><section className={styles.panel}><div className={styles.panelHeading}><h2>Available tournaments</h2><span>{tournaments.length} visible</span></div>{loading?<div className={styles.loading}><span/><span/><span/></div>:tournaments.length?<div className={styles.rows}>{tournaments.map((item)=><Link href={`/app/player/tournaments?join=${encodeURIComponent(item.slug)}`} key={item.id}><Gamepad2/><span><strong>{item.title}</strong><small>{format(item.game)} · {item.entry_fee?`KES ${number(item.entry_fee)}`:'Free entry'} · {item.player_count||0}/${item.size||'—'} entries</small></span><em>{item.status||'open'}</em><ArrowRight size={16}/></Link>)}</div>:<div className={styles.missing}><Trophy/><h2>No public tournament is available</h2><p>Return later or adjust your game profile for future recommendations.</p></div>}</section></div>}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <section><span>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></section>}
function Check({label,complete,help}:{label:string;complete:boolean;help:string}){return <div><span className={complete?styles.checkDone:styles.checkBlock}>{complete?<CheckCircle2/>:<CircleAlert/>}</span><div><strong>{label}</strong><small>{help}</small></div><em>{complete?'Ready':'Required'}</em></div>}
function format(value:string|null|undefined){return String(value||'Not set').replace(/_/g,' ').replace(/\b\w/g,(letter)=>letter.toUpperCase())}function number(value:number|null|undefined){return new Intl.NumberFormat('en-KE').format(Number(value||0))}function date(value:string|null|undefined){return value?new Intl.DateTimeFormat('en-KE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Africa/Nairobi'}).format(new Date(value)):'Not set'}
