// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(app)/bounties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bounties">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/bounties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/challenges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/challenges">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/challenges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feed">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/lobbies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lobbies/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/lobbies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/lobbies/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lobbies/create">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/lobbies/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/lobbies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lobbies">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/lobbies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/match/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/match/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/match/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/matches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matches">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/matches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/profile/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/profile/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/queue/active/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/queue/active">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/queue/active/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/queue">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/rewards/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rewards/catalog">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/rewards/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/rewards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rewards">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/rewards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/share/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/share/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/streams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/streams">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/streams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/suggest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suggest">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/suggest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/t/[slug]/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/t/[slug]/live">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/t/[slug]/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/t/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/t/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/t/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/tournaments/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/create">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/tournaments/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/bounties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bounties">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/bounties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/instagram/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/instagram">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/instagram/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/lobbies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/lobbies">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/lobbies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/matches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/matches">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/matches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/queue">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/rewards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rewards">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/rewards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tournaments">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/banned/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/banned">> = Specific
  const handler = {} as typeof import("../../../src/app/banned/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/join/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join/[code]">> = Specific
  const handler = {} as typeof import("../../../src/app/join/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/manual-tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manual-tests">> = Specific
  const handler = {} as typeof import("../../../src/app/manual-tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../../src/app/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/s/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/s/[username]">> = Specific
  const handler = {} as typeof import("../../../src/app/s/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/s/match/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/s/match/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/s/match/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/s/t/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/s/t/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/s/t/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../../src/app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/user-data-deletion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user-data-deletion">> = Specific
  const handler = {} as typeof import("../../../src/app/user-data-deletion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/bounties/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bounties/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/bounties/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/bounties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bounties">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/bounties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/instagram/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/instagram/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/instagram/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/lobbies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lobbies/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/lobbies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/lobbies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lobbies">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/lobbies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/matches/[id]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/matches/[id]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/matches/[id]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/matches/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/matches/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/matches/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/matches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/matches">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/matches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/queue/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/queue/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/queue/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/queue/reconcile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/queue/reconcile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/queue/reconcile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/queue">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/rewards/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rewards/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/rewards/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/rewards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rewards">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/rewards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/support/[id]/reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/support/[id]/reply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/support/[id]/reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/support/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/support/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/support/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/support">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/tournaments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tournaments/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/tournaments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/tournaments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tournaments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/tournaments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/whatsapp/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/whatsapp/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/whatsapp/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/magic-link/consume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-link/consume">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/magic-link/consume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/magic-link/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-link/request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/magic-link/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/password/forgot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password/forgot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/password/forgot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/password/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password/reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/password/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/bounties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bounties">> = Specific
  const handler = {} as typeof import("../../../src/app/api/bounties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/challenges/[id]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/[id]/accept">> = Specific
  const handler = {} as typeof import("../../../src/app/api/challenges/[id]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/challenges/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/challenges/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/challenges/[id]/decline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/[id]/decline">> = Specific
  const handler = {} as typeof import("../../../src/app/api/challenges/[id]/decline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/challenges/players/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges/players">> = Specific
  const handler = {} as typeof import("../../../src/app/api/challenges/players/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/challenges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/challenges">> = Specific
  const handler = {} as typeof import("../../../src/app/api/challenges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/rank-decay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/rank-decay">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/rank-decay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/season-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/season-reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/season-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/instagram/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/instagram/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/instagram/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/chezahub/link-confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/chezahub/link-confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/chezahub/link-confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/integrations/chezahub/order-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/chezahub/order-event">> = Specific
  const handler = {} as typeof import("../../../src/app/api/integrations/chezahub/order-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invite/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invite/[code]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invite/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lobbies/[id]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies/[id]/join">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lobbies/[id]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lobbies/[id]/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies/[id]/leave">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lobbies/[id]/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lobbies/[id]/result/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies/[id]/result">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lobbies/[id]/result/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lobbies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lobbies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lobbies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lobbies">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lobbies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/[id]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/[id]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/[id]/dispute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/dispute">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/[id]/dispute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/[id]/escalate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/escalate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/[id]/escalate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/[id]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]/report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/[id]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/current">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matches/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matches/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matches/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/matchmaking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/matchmaking">> = Specific
  const handler = {} as typeof import("../../../src/app/api/matchmaking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/og/match/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/match">> = Specific
  const handler = {} as typeof import("../../../src/app/api/og/match/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/og/profile/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/og/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/og/tournament/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og/tournament">> = Specific
  const handler = {} as typeof import("../../../src/app/api/og/tournament/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/paystack/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paystack/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/paystack/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queue/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/active">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queue/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queue/count/[game]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/count/[game]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queue/count/[game]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queue/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/join">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queue/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queue/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/leave">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queue/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queue/players/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/players">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queue/players/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queue/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queue/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rewards/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rewards/catalog">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rewards/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rewards/link/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rewards/link/start">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rewards/link/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rewards/redeem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rewards/redeem">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rewards/redeem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rewards/share-action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rewards/share-action">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rewards/share-action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rewards/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rewards/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rewards/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/share/match/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/match/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/share/match/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/share/profile/[username]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share/profile/[username]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/share/profile/[username]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/streams/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/streams/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/streams/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/streams/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/streams/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/streams/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/streams/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/streams/heartbeat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/streams/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/streams/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/streams/token">> = Specific
  const handler = {} as typeof import("../../../src/app/api/streams/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/streams/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/streams/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/streams/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscriptions/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscriptions/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscriptions/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscriptions/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscriptions/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscriptions/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/suggestions/[id]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggestions/[id]/vote">> = Specific
  const handler = {} as typeof import("../../../src/app/api/suggestions/[id]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggestions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/test-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/api/test-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tournaments/[slug]/advance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[slug]/advance">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tournaments/[slug]/advance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tournaments/[slug]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[slug]/join">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tournaments/[slug]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tournaments/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tournaments/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tournaments/[slug]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[slug]/start">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tournaments/[slug]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tournaments/[slug]/verify-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[slug]/verify-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tournaments/[slug]/verify-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tournaments/host-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/host-access">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tournaments/host-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tournaments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tournaments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/achievements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/achievements">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/achievements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/leaderboard/[game]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/leaderboard/[game]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/leaderboard/[game]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/profile/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/profile/media">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/profile/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/instagram/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/instagram">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/instagram/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/whatsapp/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/whatsapp/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
