ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS rating_ludo integer NOT NULL DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS wins_ludo integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS losses_ludo integer NOT NULL DEFAULT 0;
