CREATE TABLE IF NOT EXISTS public.passport_product_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name text NOT NULL,
  subject_user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_kind text NOT NULL DEFAULT 'anonymous',
  purpose text NOT NULL DEFAULT 'product_measurement',
  pii_classification text NOT NULL DEFAULT 'pseudonymous',
  source text NOT NULL,
  properties jsonb NOT NULL DEFAULT '{}'::jsonb,
  dedupe_key text NOT NULL UNIQUE,
  schema_version smallint NOT NULL DEFAULT 1,
  occurred_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  expires_at timestamptz NOT NULL DEFAULT (timezone('utc', now()) + interval '180 days'),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT passport_product_events_name_allowed CHECK (event_name IN (
    'passport_created',
    'passport_publication_changed',
    'passport_onboarding_completed',
    'passport_game_added',
    'passport_five_games_reached',
    'passport_current_game_added',
    'passport_record_claimed',
    'passport_comparison_completed',
    'passport_card_generated',
    'passport_card_shared',
    'passport_public_viewed',
    'passport_cv_viewed',
    'passport_cv_downloaded',
    'passport_friend_action',
    'passport_replay_generated',
    'passport_replay_shared'
  )),
  CONSTRAINT passport_product_events_actor_allowed CHECK (
    actor_kind IN ('anonymous', 'owner', 'friend', 'member', 'system')
  ),
  CONSTRAINT passport_product_events_purpose_fixed CHECK (purpose = 'product_measurement'),
  CONSTRAINT passport_product_events_pii_allowed CHECK (
    pii_classification IN ('none', 'pseudonymous')
  ),
  CONSTRAINT passport_product_events_source_length CHECK (char_length(source) BETWEEN 2 AND 80),
  CONSTRAINT passport_product_events_properties_object CHECK (jsonb_typeof(properties) = 'object'),
  CONSTRAINT passport_product_events_dedupe_key_format CHECK (
    dedupe_key ~ '^[a-f0-9]{64}$'
  ),
  CONSTRAINT passport_product_events_retention_bounded CHECK (
    expires_at > occurred_at AND expires_at <= occurred_at + interval '181 days'
  )
);

CREATE INDEX IF NOT EXISTS passport_product_events_name_time_idx
  ON public.passport_product_events(event_name, occurred_at DESC);
CREATE INDEX IF NOT EXISTS passport_product_events_subject_time_idx
  ON public.passport_product_events(subject_user_id, occurred_at DESC)
  WHERE subject_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS passport_product_events_expiry_idx
  ON public.passport_product_events(expires_at);

ALTER TABLE public.passport_product_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.passport_product_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.passport_product_events_id_seq FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.passport_product_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.passport_product_events_id_seq TO service_role;

CREATE OR REPLACE FUNCTION private.emit_passport_product_event(
  p_event_name text,
  p_subject_user_id uuid,
  p_actor_kind text,
  p_source text,
  p_properties jsonb,
  p_dedupe_seed text,
  p_occurred_at timestamptz DEFAULT timezone('utc', now())
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.passport_product_events(
    event_name,
    subject_user_id,
    actor_kind,
    source,
    properties,
    dedupe_key,
    occurred_at,
    expires_at
  )
  VALUES (
    p_event_name,
    p_subject_user_id,
    p_actor_kind,
    p_source,
    coalesce(p_properties, '{}'::jsonb),
    encode(extensions.digest(p_event_name || ':' || coalesce(p_subject_user_id::text, 'anonymous') || ':' || p_dedupe_seed, 'sha256'), 'hex'),
    p_occurred_at,
    p_occurred_at + interval '180 days'
  )
  ON CONFLICT (dedupe_key) DO NOTHING;
END;
$$;
REVOKE ALL ON FUNCTION private.emit_passport_product_event(text, uuid, text, text, jsonb, text, timestamptz)
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.capture_passport_profile_product_events()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM private.emit_passport_product_event(
      'passport_created', NEW.user_id, 'owner', 'database.passport_profiles',
      jsonb_build_object('creation_source', 'owner'), NEW.user_id::text, NEW.created_at
    );
    RETURN NEW;
  END IF;

  IF NEW.publication_status IS DISTINCT FROM OLD.publication_status
    OR NEW.is_discoverable IS DISTINCT FROM OLD.is_discoverable
    OR NEW.default_visibility IS DISTINCT FROM OLD.default_visibility
  THEN
    PERFORM private.emit_passport_product_event(
      'passport_publication_changed', NEW.user_id, 'owner', 'database.passport_profiles',
      jsonb_build_object(
        'publication_status', NEW.publication_status,
        'discoverable', NEW.is_discoverable,
        'default_visibility', NEW.default_visibility
      ),
      NEW.user_id::text || ':' || NEW.public_version::text,
      NEW.updated_at
    );
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.capture_passport_profile_product_events()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS passport_profiles_capture_product_events ON public.passport_profiles;
CREATE TRIGGER passport_profiles_capture_product_events
AFTER INSERT OR UPDATE OF publication_status, is_discoverable, default_visibility
ON public.passport_profiles
FOR EACH ROW EXECUTE FUNCTION private.capture_passport_profile_product_events();

CREATE OR REPLACE FUNCTION private.capture_passport_game_product_events()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_game_count integer;
  v_current_game_count integer;
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM private.emit_passport_product_event(
      'passport_game_added', NEW.user_id, 'owner', 'database.passport_game_entries',
      jsonb_build_object(
        'play_status', NEW.play_status,
        'source_type', NEW.source_type,
        'visibility', NEW.visibility
      ),
      NEW.id::text,
      NEW.created_at
    );

    SELECT count(*)::integer INTO v_game_count
    FROM public.passport_game_entries
    WHERE user_id = NEW.user_id;

    IF v_game_count >= 5 THEN
      PERFORM private.emit_passport_product_event(
        'passport_five_games_reached', NEW.user_id, 'owner', 'database.passport_game_entries',
        jsonb_build_object('game_count_at_milestone', v_game_count),
        NEW.user_id::text,
        NEW.created_at
      );
    END IF;
  END IF;

  IF NEW.play_status = 'playing'
    AND (TG_OP = 'INSERT' OR OLD.play_status IS DISTINCT FROM NEW.play_status)
  THEN
    PERFORM private.emit_passport_product_event(
      'passport_current_game_added', NEW.user_id, 'owner', 'database.passport_game_entries',
      jsonb_build_object('source_type', NEW.source_type, 'visibility', NEW.visibility),
      NEW.id::text,
      coalesce(NEW.updated_at, NEW.created_at)
    );
  END IF;

  SELECT count(*)::integer INTO v_current_game_count
  FROM public.passport_game_entries
  WHERE user_id = NEW.user_id AND play_status = 'playing';
  IF v_game_count IS NULL THEN
    SELECT count(*)::integer INTO v_game_count
    FROM public.passport_game_entries
    WHERE user_id = NEW.user_id;
  END IF;
  IF v_game_count >= 5 AND v_current_game_count >= 1 THEN
    PERFORM private.emit_passport_product_event(
      'passport_onboarding_completed', NEW.user_id, 'owner', 'database.passport_game_entries',
      jsonb_build_object('completion_version', 'five_games_plus_current_v1'),
      NEW.user_id::text || ':five_games_plus_current_v1',
      coalesce(NEW.updated_at, NEW.created_at)
    );
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.capture_passport_game_product_events()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS passport_games_capture_product_events ON public.passport_game_entries;
CREATE TRIGGER passport_games_capture_product_events
AFTER INSERT OR UPDATE OF play_status ON public.passport_game_entries
FOR EACH ROW EXECUTE FUNCTION private.capture_passport_game_product_events();

CREATE OR REPLACE FUNCTION private.capture_passport_record_product_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM private.emit_passport_product_event(
    'passport_record_claimed', NEW.user_id, 'system', 'database.passport_verification_records',
    jsonb_build_object(
      'subject_type', NEW.subject_type,
      'verification_state', NEW.verification_state,
      'source_type', NEW.source_type
    ),
    NEW.id::text,
    NEW.issued_at
  );
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.capture_passport_record_product_event()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS passport_records_capture_product_event ON public.passport_verification_records;
CREATE TRIGGER passport_records_capture_product_event
AFTER INSERT ON public.passport_verification_records
FOR EACH ROW EXECUTE FUNCTION private.capture_passport_record_product_event();

CREATE OR REPLACE FUNCTION private.capture_passport_friend_product_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_subject uuid;
  v_action text;
  v_at timestamptz;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_subject := OLD.requested_by;
    v_at := coalesce(OLD.updated_at, timezone('utc', now()));
  ELSE
    v_subject := NEW.requested_by;
    v_at := coalesce(NEW.updated_at, timezone('utc', now()));
  END IF;
  v_action := CASE
    WHEN TG_OP = 'DELETE' THEN 'removed'
    WHEN TG_OP = 'INSERT' THEN 'requested'
    WHEN NEW.status = 'accepted' AND OLD.status IS DISTINCT FROM NEW.status THEN 'accepted'
    WHEN NEW.status = 'declined' AND OLD.status IS DISTINCT FROM NEW.status THEN 'declined'
    ELSE 'updated'
  END;
  PERFORM private.emit_passport_product_event(
    'passport_friend_action', v_subject, 'owner', 'database.passport_friendships',
    jsonb_build_object('action', v_action),
    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END::text
      || ':' || v_action || ':' || txid_current()::text,
    v_at
  );
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.capture_passport_friend_product_event()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS passport_friendships_capture_product_event ON public.passport_friendships;
CREATE TRIGGER passport_friendships_capture_product_event
AFTER INSERT OR UPDATE OF status OR DELETE ON public.passport_friendships
FOR EACH ROW EXECUTE FUNCTION private.capture_passport_friend_product_event();

CREATE OR REPLACE FUNCTION private.capture_passport_replay_product_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM private.emit_passport_product_event(
    'passport_replay_generated', NEW.user_id, 'owner', 'database.passport_replay_snapshots',
    jsonb_build_object('replay_year', NEW.replay_year, 'period_state', NEW.period_state),
    NEW.id::text || ':' || extract(epoch FROM NEW.generated_at)::bigint::text,
    NEW.generated_at
  );
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.capture_passport_replay_product_event()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS passport_replays_capture_product_event ON public.passport_replay_snapshots;
CREATE TRIGGER passport_replays_capture_product_event
AFTER INSERT OR UPDATE OF generated_at ON public.passport_replay_snapshots
FOR EACH ROW EXECUTE FUNCTION private.capture_passport_replay_product_event();

CREATE OR REPLACE FUNCTION public.cleanup_passport_operational_data()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_intents integer := 0;
  v_sync_runs integer := 0;
  v_api_events integer := 0;
  v_deliveries integer := 0;
  v_ecosystem_events integer := 0;
  v_product_events integer := 0;
  v_operation_runs integer := 0;
BEGIN
  DELETE FROM public.passport_connection_intents WHERE expires_at < timezone('utc', now()) - interval '7 days';
  GET DIAGNOSTICS v_intents = ROW_COUNT;
  DELETE FROM public.passport_provider_sync_runs WHERE started_at < timezone('utc', now()) - interval '180 days';
  GET DIAGNOSTICS v_sync_runs = ROW_COUNT;
  DELETE FROM public.passport_developer_api_events WHERE occurred_at < timezone('utc', now()) - interval '90 days';
  GET DIAGNOSTICS v_api_events = ROW_COUNT;
  DELETE FROM public.passport_webhook_deliveries WHERE status IN ('delivered', 'failed', 'cancelled') AND updated_at < timezone('utc', now()) - interval '30 days';
  GET DIAGNOSTICS v_deliveries = ROW_COUNT;
  DELETE FROM public.passport_ecosystem_events event
  WHERE event.created_at < timezone('utc', now()) - interval '180 days'
    AND NOT EXISTS (
      SELECT 1 FROM public.passport_webhook_deliveries delivery
      WHERE delivery.ecosystem_event_id = event.id AND delivery.status IN ('pending', 'retry', 'delivering')
    );
  GET DIAGNOSTICS v_ecosystem_events = ROW_COUNT;
  DELETE FROM public.passport_product_events WHERE expires_at < timezone('utc', now());
  GET DIAGNOSTICS v_product_events = ROW_COUNT;
  DELETE FROM public.passport_operation_runs WHERE started_at < timezone('utc', now()) - interval '180 days';
  GET DIAGNOSTICS v_operation_runs = ROW_COUNT;
  RETURN jsonb_build_object(
    'connection_intents', v_intents,
    'sync_runs', v_sync_runs,
    'developer_api_events', v_api_events,
    'webhook_deliveries', v_deliveries,
    'ecosystem_events', v_ecosystem_events,
    'product_events', v_product_events,
    'operation_runs', v_operation_runs
  );
END;
$$;
REVOKE ALL ON FUNCTION public.cleanup_passport_operational_data() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_passport_operational_data() TO service_role;
