CREATE TABLE IF NOT EXISTS public.passport_route_diagnostics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_name text NOT NULL,
  request_id_hash text NOT NULL,
  subject_hash text,
  operation text,
  response_status smallint NOT NULL,
  duration_ms integer NOT NULL,
  result_class text NOT NULL,
  cache_state text,
  occurred_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  expires_at timestamptz NOT NULL DEFAULT (timezone('utc', now()) + interval '30 days'),
  CONSTRAINT passport_route_diagnostics_route_allowed CHECK (route_name IN (
    'passport_public_api', 'passport_public_page', 'passport_card',
    'passport_comparison', 'passport_cv_page', 'passport_cv_pdf'
  )),
  CONSTRAINT passport_route_diagnostics_request_hash CHECK (request_id_hash ~ '^[a-f0-9]{64}$'),
  CONSTRAINT passport_route_diagnostics_subject_hash CHECK (subject_hash IS NULL OR subject_hash ~ '^[a-f0-9]{20}$'),
  CONSTRAINT passport_route_diagnostics_status_range CHECK (response_status BETWEEN 100 AND 599),
  CONSTRAINT passport_route_diagnostics_duration_range CHECK (duration_ms BETWEEN 0 AND 600000),
  CONSTRAINT passport_route_diagnostics_result_allowed CHECK (result_class IN (
    'success', 'not_found', 'restricted', 'invalid', 'unauthorized',
    'rate_limited', 'storage_error', 'render_fallback', 'internal_error'
  )),
  CONSTRAINT passport_route_diagnostics_operation_length CHECK (operation IS NULL OR char_length(operation) <= 40),
  CONSTRAINT passport_route_diagnostics_cache_length CHECK (cache_state IS NULL OR char_length(cache_state) <= 40),
  CONSTRAINT passport_route_diagnostics_expiry CHECK (expires_at > occurred_at AND expires_at <= occurred_at + interval '31 days')
);

CREATE INDEX IF NOT EXISTS passport_route_diagnostics_route_time_idx
  ON public.passport_route_diagnostics(route_name, occurred_at DESC);
CREATE INDEX IF NOT EXISTS passport_route_diagnostics_status_time_idx
  ON public.passport_route_diagnostics(response_status, occurred_at DESC);
CREATE INDEX IF NOT EXISTS passport_route_diagnostics_expiry_idx
  ON public.passport_route_diagnostics(expires_at);

ALTER TABLE public.passport_route_diagnostics ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.passport_route_diagnostics FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.passport_route_diagnostics_id_seq FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.passport_route_diagnostics TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.passport_route_diagnostics_id_seq TO service_role;
